### PR TITLE
Ft log in page 160171503

### PR DESCRIPTION
**Pull request by NtaleShadik**
This commit Delivers a log in page for the Events app

srnshot2

### CODE REVIEW

**Comment by okellogabrielinnocent** [comment]
Nice work
Please separate image folder from css folder

**Comment by sekayasin** [comment]
Bravo bro!

**Comment by mariamiah** [comment]
This is great

**Comment by NtaleShadik** [comment]
haden't realised that the image folder was inside the css, Modified it though

**Comment by AldridgeAA** [comment]
Great work

**Pull request merged**
